# Generated by Django 5.2.4 on 2025-10-22 20:56

from django.db import migrations

from . import init, init_reverse


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(init, init_reverse),
    ]
