# Generated by Django 5.2.13 on 2026-04-25 11:58

from django.db import migrations
from . import init, init_reverse


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(init, init_reverse),
    ]
