# Generated by Django 5.2.4 on 2025-11-13 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = []
