# Generated by Django 6.0.5 on 2026-07-02 19:34

from . import init, init_reverse
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [migrations.RunPython(init, init_reverse)]
