# Generated by Django 6.1 on 2026-09-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "language",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="The language to translate to",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
