name: Pyre

on:
  [push]
  # pull_request:
  #   branches:
  #     - master

jobs:
  pyre:
    runs-on: docker
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Setup python
        uses: docker://python:3.11.10

      - name: Install deps
        run: |
          apt-get update && apt-get install -y \
          python3-pip \
          python3-dev \
          build-essential \
          libffi-dev \
          libssl-dev \
          libxml2-dev \
          libxslt-dev \
          zlib1g-dev
          python3 -m pip install --upgrade pip

      - name: Restore Venv
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: venv

      - name: Install Pyre dep
        run: |
          pip install --upgrade setuptools
          pip install pdm wheel
          python3 -m pip install --upgrade pdm
          pdm install --prod --no-editable --fail-fast

      - name: Save venv
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .venv
          key: venv

      - name: Restore Pyre cache
        uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: .pyre
          key: pyre-cache

      - name: Pyre analysis
        run: |
          . .venv/bin/activate
          pyre --output=json | python3 -m json.tool

      - name: Pysa analysis
        run: |
          # . .venv/bin/activate
          pyre --noninteractive analyze --no-verify --use-cache --output-format json

      - name: Save Pyre cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .pyre
          key: pyre-cache
