name: Pyre

on:
  [push]
  # pull_request:
  #   branches:
  #     - master

jobs:
  pyre:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.13.0-alpha.1"]
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install stuff
        run: |
          cat /etc/os-release

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"
          architecture: "x64"
          allow-prereleases: true
          # check-latest: false
          # token: ***
          # update-environment: true
        env:
          RUNNER_ALLOW_RUNASROOT: true
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: Restore Venv
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: venv

      - name: Install Pyre dep
        run: |
          python3 -m venv .venv
          . .venv/source/activate
          pip install -r requirements.txt

      - name: Save venv
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .venv
          key: venv

      - name: Restore Pyre cache
        uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: .pyre
          key: pyre-cache

      - name: Pyre analysis
        run: |
          . .venv/bin/activate
          pyre --output=json | python3 -m json.tool

      - name: Pysa analysis
        run: |
          # . .venv/bin/activate
          pyre --noninteractive analyze --no-verify --use-cache --output-format json

      - name: Save Pyre cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .pyre
          key: pyre-cache
