name: Pyre

on:
  [push]
  # pull_request:
  #   branches:
  #     - master

jobs:
  pyre:
    runs-on: docker
    container:
      image: python:3.11.10
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Restore Venv
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: venv

      - name: Install Pyre dep
        # uses: docker://docker.io/iliyankostov/python-pdm-aarch64:3.11
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Save venv
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .venv
          key: venv

      - name: Restore Pyre cache
        uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: .pyre
          key: pyre-cache

      - name: Pyre analysis
        run: |
          . .venv/bin/activate
          pyre --output=json | python3 -m json.tool

      - name: Pysa analysis
        run: |
          # . .venv/bin/activate
          pyre --noninteractive analyze --no-verify --use-cache --output-format json

      - name: Save Pyre cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .pyre
          key: pyre-cache
