version: 2.1

executors:
  docker-python:
    docker:
      - image: cimg/base:2024.09
      - image: cimg/python:3.11-node
    # working_directory: /tmp

jobs:
  build:
    executor: docker-python
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Create venv
          command: |
            python --version
            python -m venv .venv
      - run:
          name: Install Pyre deps
          command: |
            . .venv/bin/activate
            echo "Now installing pyre deps..."
            pip install --upgrade setuptools
            sudo apt-get update && sudo apt-get install -y watchman
            pip install wheel pyre-check fb-sapp watchman
      - save_cache:
          paths:
            - .venv
          key: v1-portolio-{{ .Environment.CIRCLE_SHA1  }}
      - persist_to_workspace:
          root: .
          paths:
            - src
            - stubs
            - .pyre_configuration
            - tests

  perform-analysis:
    executor: docker-python
    steps:
      - restore_cache:
          key: v1-portolio-{{ .Environment.CIRCLE_SHA1  }}
      - attach_workspace:
          at: .
      - run:
          name: Pyre analysis
          command: |
            ls -1 -a
            . .venv/bin/activate
            echo "Now performing analysis..."
            pyre --output=json | python3 -m json.tool
            pyre --noninteractive analyze --no-verify --output-format json

workflows:
  security-analysis:
    jobs:
      - build
      - perform-analysis:
          requires:
            - build
