---
- name: Bulgarian
  proficiency: "Native"
  row: 1
  icon: "bulgaria.svg"

- name: English
  proficiency: "Fluent"
  row: 1
  icon: "united-kingdom.svg"

- name: German
  proficiency: "Beginner"
  row: 1
  icon: "germany.svg"

- name: French
  proficiency: "Beginner"
  row: 1
  icon: "france.svg"
