# Generated by Django 5.1.1 on 2024-10-21 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="project name")),
                (
                    "link",
                    models.CharField(max_length=100, verbose_name="Link to project"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=2000, verbose_name="Short description of the project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Name of the user"),
                ),
                (
                    "email",
                    models.EmailField(max_length=200, verbose_name="Email of the user"),
                ),
                (
                    "<django.db.models.fields.CharField>-avatar",
                    models.ImageField(height_field=300, upload_to="", width_field=300),
                ),
                ("skills", models.CharField(max_length=200, verbose_name="Skillsets")),
                (
                    "projects",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="landing_page.project",
                    ),
                ),
            ],
        ),
    ]
