# Generated by Django 5.2.4 on 2025-08-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="projects",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
