# Generated by Django 5.2.4 on 2025-08-15 20:25

from django.db import migrations

from . import init, init_reverse


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(init, init_reverse),
    ]
