# Generated by Django 5.2.4 on 2025-08-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("landing_page", "0002_remove_user_projects_delete_project_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnologyCategory",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Name of the technology category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnologyStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Name of the technology"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        max_length=20, verbose_name="Icon name of the technology"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="landing_page.technologycategory",
                        verbose_name="Category of the technology",
                    ),
                ),
            ],
        ),
    ]
