# Generated by Django 5.2.4 on 2025-08-14 11:59


from django.db import migrations
from landing_page.data_class.portfolio.technology import Technology
from landing_page.data_class.portfolio.technology_category import TechnologyCategory


def init(apps, schema_editor):
    TechnologyCategory.table_create(apps)
    Technology.table_create(apps)


def init_reverse(apps, schema_editor):
    """
    NOTE: Keep it because it'll complain when you make `make sql-init-test`
    """


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0005_rename_technologystack_technology"),
    ]

    operations = [
        migrations.RunPython(init, init_reverse),
    ]
