# Generated by Django 5.2.4 on 2025-08-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Name of the technology"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        max_length=20, verbose_name="Icon name of the technology"
                    ),
                ),
                (
                    "row",
                    models.IntegerField(verbose_name="Row number of the technology"),
                ),
                (
                    "page",
                    models.IntegerField(verbose_name="Page number of the technology"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing_page.technologycategory",
                        verbose_name="Category of the technology",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TechnologyStack",
        ),
    ]
