# Generated by Django 5.2.4 on 2025-08-14 11:59


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0004_technology_delete_technologystack"),
    ]

    operations = []
