# Generated by Django 5.2.4 on 2025-08-14 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0003_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TechnologyStack",
            new_name="Technology",
        ),
    ]
