# Generated by Django 5.2.4 on 2025-08-14 16:04

from django.db import migrations

from . import init, init_reverse


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0004_technology_delete_technologystack"),
    ]

    operations = [
        migrations.RunPython(init, init_reverse),
    ]
