# Generated by Django 5.2.4 on 2025-08-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0004_auto_20250814_1359"),
        ("landing_page", "0005_auto_20250814_1804"),
    ]

    operations = []
