# Generated by Django 5.2.4 on 2025-08-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0006_merge_0004_auto_20250814_1359_0005_auto_20250814_1804"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        max_length=30, verbose_name="Image of the certificate"
                    ),
                ),
                (
                    "row",
                    models.IntegerField(verbose_name="Row number of the certificate"),
                ),
                ("date", models.CharField(verbose_name="Date of the certificate")),
                ("name", models.CharField(verbose_name="Name of the certificate")),
                (
                    "url",
                    models.CharField(verbose_name="Url of the certificate to verify"),
                ),
                (
                    "style",
                    models.CharField(
                        max_length=300, verbose_name="Custom css of the certificate"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(max_length=100, verbose_name="Degree name"),
                ),
                (
                    "specialty",
                    models.CharField(max_length=100, verbose_name="Specialty name"),
                ),
                (
                    "university_name",
                    models.CharField(max_length=50, verbose_name="University name"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=300, verbose_name="Description of the education"
                    ),
                ),
                (
                    "scroll_description",
                    models.BooleanField(
                        verbose_name="Whether or not the description should be scrollable or not"
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        max_length=30, verbose_name="Image of the education"
                    ),
                ),
                (
                    "href_tooltip",
                    models.CharField(
                        max_length=30, verbose_name="Href tooltip of the education"
                    ),
                ),
                (
                    "href_title",
                    models.CharField(
                        max_length=200, verbose_name="Href title of the education"
                    ),
                ),
                ("date", models.CharField(verbose_name="Date of the education")),
                ("gpa", models.CharField(verbose_name="GPA of the education")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Name of the project"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=300, verbose_name="Description of the project"
                    ),
                ),
                (
                    "schroll_description",
                    models.BooleanField(
                        verbose_name="Whether or not the description should be scrollable or not"
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        max_length=30, verbose_name="Image of the project"
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        verbose_name="Date of the project being worked on"
                    ),
                ),
                ("row", models.IntegerField(verbose_name="Row number of the project")),
                ("urls", models.JSONField(verbose_name="Urls of the project")),
                ("project_names", models.CharField(verbose_name="Project names")),
            ],
        ),
        migrations.CreateModel(
            name="WorkHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="Company name"),
                ),
                (
                    "company_name_label",
                    models.CharField(
                        max_length=100,
                        verbose_name="Aria label of the company in pattern company-name-123",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        max_length=30, verbose_name="Image of the company"
                    ),
                ),
                (
                    "specialty",
                    models.CharField(max_length=100, verbose_name="Specialty name"),
                ),
                ("dates", models.JSONField(verbose_name="Dates of work")),
                (
                    "description",
                    models.CharField(verbose_name="Description of the work history"),
                ),
            ],
        ),
    ]
