# Generated by Django 5.2.4 on 2025-08-15 17:31

from django.db import migrations

from . import init, init_reverse


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0007_certification_education_project_workhistory"),
    ]

    operations = [
        migrations.RunPython(init, init_reverse),
    ]
