---
- title: Living abroad
  description: |
    My personal experience when moving to live from Bulgaria to France (and some tips on how to prepare if you're planning to live abroad as well)
  image_preview: plane_in_sunlight.jpg
  date: "2026-04-25"
  url: "living-abroad"
  read_time_mins: 5
  category: life
  row: 1
