---
- title: The start of something new
  description: |
    Starting a brand new idea from scratch and facing the challenges
  image_preview: zprofile.png
  date: "2025-10-04"
  url: "the-start-of-something-new"
  read_time_mins: 3
  category: zprofile
  row: 1
