---
headers:
  - Portfolio
  - Blogs

body:
  main:
    greeting: Hi
    introduction: I'm Iliyan
    catch_phrase: I try to figure out how things work.
    scroll_down: Scroll down to find out more about me
  about:
    read_more: Continue reading
    read_less: See less
    introduction: |
      As you may have already guessed from the title above, my name is indeed,
      Iliyan. I'm born in Bulgaria in a city on the coast of the Black Sea -
      Varna.
    starting_journey: |
      I have started on my engineering journey back when I was a kid and had to
      constantly fix our family desktop computer from crashing on WindowsXP and
      Windows7, where the issue might be either hardware related - ROM failed,
      motherboard got fried because of the very hot summers we had at the late
      2000s, or I installed a pirated game with additional content (aka
      malware). That repetition of breaking and fixing changed my way of
      thinking and approaching problems from there on.
    starting_uni: |
      Afterward I joined in a high school for operation of road transport.
      Yes, it's not computer related, but it's in the engineering field. I
      actually do consider myself more of an <u>engineer</u> than a computer
      scientist.
    life_change_on_uni: |
      Time passed by and then after high school I was working at a grocery
      store and like every confused 18 years old, I was wondering what I was
      going to do with my life. Then after looking of all the local Varna
      universities, I then stopped at this one, called *Technical university
      of Varna*. I got curious by the technical specialtes - mainly at
      computer science and computer technologies and internet. After a bit of
      thinking, I randomly choose the second option. That was by far the
      <span class="green">best</span> life changing choice I've made so far
      and at that time I couldn't have imagined how much this decision was
      going to change me for the better.
    a_bit_of_dumb_philosophy: |
      In there I didn't learn only about technology, I learnt about working
      with others, exchanging ideas with passionate people, engaging in
      debates with professors and assitants, and most importantly - becoming
      an adult. That's the point of an university, shaping you into a
      well-rounded individual, who can be integrated into the professional and
      social environments and being responsible for their actions. I
      concretely believe in that statement. I've heard so many pepole
      (co-students), that believe that the point of an university is to get a
      job, that person is either delusional or being a stubborn child, that
      doesn't want to look at the bigger picture.
    starting_work: |
      In the third year of my bachelor's degree (2021) I was in an internship
      of a small local financial institution, that we developed legacy Windows
      32bit for WindowsXP systems in Visual Objects community edition (also
      called CAVO). In the same year I landed my first actual IT job as a
      DevOps engineer as a consultant. The good thing about being a consultant
      is that you can see different companies (clients) with different
      architectures and <i>ways-of-working</i> in a very short amount of time,
      but the bad part is that you are not a permanent employee in these
      projects and you'll have to learn all of those tedious company's
      processes and in-house tools again for the next project. Believe me, in
      time you'll get very irritated by it.
    work_in_france: |
      After some time I've spend working there and becoming more familiar with
      the company, I started to dislike the the company culture and decided to
      go elsewhere. In May 2025, I found another job, which wasn't just a job,
      but a life change. I had to move out to live on the southern region of
      France, Côte d'Azur.
    cliche_ending: And the story continues...
