# Generated by Django 5.2.4 on 2025-10-21 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        max_length=30, verbose_name="Image of the certificate"
                    ),
                ),
                (
                    "row",
                    models.IntegerField(verbose_name="Row number of the certificate"),
                ),
                ("date", models.CharField(verbose_name="Date of the certificate")),
                ("name", models.CharField(verbose_name="Name of the certificate")),
                (
                    "url",
                    models.CharField(verbose_name="Url of the certificate to verify"),
                ),
                ("issuer", models.CharField(verbose_name="Issuer of the certificate")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(max_length=100, verbose_name="Degree name"),
                ),
                (
                    "specialty",
                    models.CharField(max_length=100, verbose_name="Specialty name"),
                ),
                (
                    "university_name",
                    models.CharField(max_length=50, verbose_name="University name"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=300, verbose_name="Description of the education"
                    ),
                ),
                (
                    "scroll_description",
                    models.BooleanField(
                        verbose_name="Whether or not the description should be scrollable or not"
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        max_length=30, verbose_name="Image of the education"
                    ),
                ),
                (
                    "href_tooltip",
                    models.CharField(
                        max_length=30, verbose_name="Href tooltip of the education"
                    ),
                ),
                (
                    "href_title",
                    models.CharField(
                        max_length=200, verbose_name="Href title of the education"
                    ),
                ),
                ("date", models.CharField(verbose_name="Date of the education")),
                ("gpa", models.CharField(verbose_name="GPA of the education")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Language")),
                (
                    "proficiency",
                    models.CharField(
                        max_length=50, verbose_name="Proficiency of the language"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        max_length=50, verbose_name="Flag of the language"
                    ),
                ),
                ("row", models.IntegerField(verbose_name="Row number of the language")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Name of the project"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=300, verbose_name="Description of the project"
                    ),
                ),
                (
                    "scroll_description",
                    models.BooleanField(
                        null=True,
                        verbose_name="Whether or not the description should be scrollable or not",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        max_length=30, verbose_name="Image of the project"
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        verbose_name="Date of the project being worked on"
                    ),
                ),
                ("row", models.IntegerField(verbose_name="Row number of the project")),
                ("repositories", models.JSONField(verbose_name="Repositories")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TechnologyCategory",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Name of the technology category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="Company name"),
                ),
                (
                    "company_name_label",
                    models.CharField(
                        max_length=100,
                        verbose_name="Aria label of the company in pattern company-name-123",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        max_length=30, verbose_name="Image of the company"
                    ),
                ),
                (
                    "specialty",
                    models.CharField(max_length=100, verbose_name="Specialty name"),
                ),
                ("dates", models.JSONField(verbose_name="Dates of work")),
                (
                    "description",
                    models.CharField(verbose_name="Description of the work history"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Name of the technology"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        max_length=20, verbose_name="Icon name of the technology"
                    ),
                ),
                (
                    "row",
                    models.IntegerField(verbose_name="Row number of the technology"),
                ),
                (
                    "page",
                    models.IntegerField(verbose_name="Page number of the technology"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.technologycategory",
                        verbose_name="Category of the technology",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
