# Generated by Django 5.2.4 on 2025-09-27 14:55

from django.db import migrations
from . import init, init_reverse


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(init, init_reverse),
    ]
