# Generated by Django 5.2.4 on 2025-11-11 18:21

from django.db import migrations

from . import init, init_reverse


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(init, init_reverse),
    ]
