# Generated by Django 6.1 on 2026-08-16 12:34

from django.db import migrations

from . import init, init_reverse


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [migrations.RunPython(init, init_reverse)]
