# Generated by Django 6.1 on 2026-09-26 18:57

from django.db import migrations

from . import init, init_reverse


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(init, init_reverse),
    ]
