name: Build LaTeX PDF

on:
  push:
    paths:
      - "docs/**.tex"
    branches:
      - master

jobs:
  build-pdf:
    name: Compile LaTeX to PDF
    runs-on: ubuntu-latest
    env:
      working-directory: docs
    strategy:
      fail-fast: false
      matrix:
        language: ["en", "fr", "bg", "ge"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install TeX Live and required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-recommended \
            texlive-lang-french \
            texlive-lang-german \
            texlive-lang-cyrillic \
            texlive-latex-extra \
            texlive-bibtex-extra \
            texlive-fonts-extra \
            biber \
            latexmk

      - name: LaTeX Compilation
        run: |
          latexmk -pdf -interaction=nonstopmode \
            -pdflatex="xelatex -interaction=nonstopmode '\def\lang{${{ matrix.language }}}\input{%S}'" \
            main.tex
        working-directory: ${{ env.working-directory }}

      - name: Prepare pdf for upload
        id: pdf
        run: |
          mkdir -p latex/portfolio/cv-${{ matrix.language }}
          cp docs/main.pdf latex/portfolio/cv-${{ matrix.language }}

      - name: Upload PDF
        uses: actions/upload-artifact@v7
        with:
          name: main-${{ matrix.language }}-pdf
          path: docs/main.pdf

      - name: Install AWS CLI
        uses: docker://amazon/aws-cli:2.33.2
        with:
          args: s3 sync latex s3://${{ secrets.PORTFOLIO_S3_MAIN_PROD_BUCKET }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PORTFOLIO_S3_MAIN_PROD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PORTFOLIO_S3_MAIN_PROD_SECRET_ACESS_KEY }}
          AWS_BUCKET: ${{ secrets.PORTFOLIO_S3_MAIN_PROD_BUCKET }}
