name: SonarCloud scanner

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ik-portfolio
          SONAR_ORGANIZATION: iliyankostov9
          SONAR_BRANCH_NAME: ${{ github.head_ref }}

      - name: Analyze with SonarCloud
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarcloud-github-action@v3.0.0
        # with:
        #   args: |
        #     -Dsonar.branch.name=${{ github.head_ref }}

      - name: "SonarQube Quality result"
        run: |
          echo "Quality Gate status: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
