name: Terraform workflow

on:
  push:
    branches:
      - master
      - feature/terraform
    # paths:
    #   - infra/iac/**
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform job
    permissions:
      contents: read
      pull-requests: write
    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Age
        uses: AnimMouse/setup-age@v1

      - name: Decrypt terraform.tfvars
        run: |
          echo "${{ secrets.PORTFOLIO_AGE_KEY }}" >> age-key.txt
          ls
          age --decrypt -i age-key.txt terraform.tfvars.age > terraform.tfvars
        working-directory: infra/iac/env/prod

      - name: Setup terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 #v4
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: "1.9.5"

      - name: Initialize
        run: make tf-init

      - name: Validate
        if: success() || failure()
        run: make tf-validate

      - name: Plan
        run: make tf-plan

      - name: Apply
        run: make tf-apply
