name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

    branches:
      - master
    paths:
      - "**"
      - "!.gitignore"
      - "!README.md"

jobs:
  checkout:
    name: Checkout repo
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Save repo to artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio
          path: .
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 0

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: checkout
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11.9"]

    steps:
      - name: Download repo artifact
        uses: actions/download-artifact@v5
        with:
          name: portfolio
          path: .

      - name: Unit test
        run: echo "It works!"

      - name: List files
        run: ls -1 -a

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: test

    steps:
      - name: Download repo artifact
        uses: actions/download-artifact@v5
        with:
          name: portfolio
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install lint dependencies
        run: pip install black flake8 pylint

      - name: Pylint
        run: |
          pylint .

      - name: Black
        run: |
          black --check .

      - name: Flake8
        run: |
          flake8 .

  type-checking:
    name: Pyre testing
    runs-on: ubuntu-latest
    needs: test
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11.9"]

    steps:
      - name: Download repo artifact
        uses: actions/download-artifact@v5
        with:
          name: portfolio
          path: .

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version  }}"
          allow-prereleases: true

      - name: Restore Venv
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Install PDM
        run: |
          pip install --upgrade pip
          pip install pdm setuptools-rust

      - name: Install deps
        run: pdm install

      - name: Save venv
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Restore Pyre cache
        uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: .pyre
          key: pyre-cache

      - name: Pyre analysis
        run: |
          . .venv/bin/activate
          pdm add pyre-check fb-sapp
          pyre --output=json | python3 -m json.tool

      - name: Pysa analysis
        run: |
          . .venv/bin/activate
          pyre --noninteractive analyze --no-verify --use-cache --output-format json

      - name: Save Pyre cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .pyre
          key: pyre-cache
