name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

    branches:
      - master
    paths:
      - "src/**"
      - "uv.lock"
      - "pyproject.toml"
      - "flake.lock"
      - "!.gitignore"
      - "!README.md"

env:
  PORTFOLIO_SKIP_SECRET_KEY_CHECK: true
  PORTFOLIO_SKIP_CDN_URL_CHECK: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: |
            src
            pyproject.toml
            uv.lock
            flake.nix
            flake.lock
          sparse-checkout-cone-mode: true

      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
        with:
          name: iliyankostov9-portfolio-dev
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: devenv
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv

      - name: Run tests
        shell: bash -c "nix develop --impure .#dev -c bash -- {0}"
        run: |
          devenv test

      - name: Save venv
        uses: actions/cache/save@v6
        if: steps.cache-venv.outputs.cache-hit != 'true'
        with:
          path: .devenv
          key: devenv-${{ runner.os }}-${{ github.run_id }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: test
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: |
            src
            test
            Makefile
            pyproject.toml
            uv.lock
            flake.nix
            flake.lock
          sparse-checkout-cone-mode: true

      - name: Restore venv
        uses: actions/cache/restore@v6
        with:
          path: .devenv
          key: devenv-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
        with:
          name: iliyankostov9-portfolio-dev
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: devenv
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv

      - name: Pylint
        shell: bash -c "nix develop --impure .#dev -c bash -- {0}"
        run: |
          pylint src stubs

      - name: Black
        shell: bash -c "nix develop --impure .#dev -c bash -- {0}"
        run: |
          black --check --diff .

      - name: Flake8
        shell: bash -c "nix develop --impure .#dev -c bash -- {0}"
        run: |
          flake8 .
