name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

    branches:
      - master
    paths:
      - "**"
      - "!.gitignore"
      - "!README.md"

env:
  PYRE_SKIP: true

jobs:
  checkout:
    name: Checkout repo
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Save repo to artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio
          path: .
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 0

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: checkout
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11.9"]
    steps:
      - name: Download repo artifact
        uses: actions/download-artifact@v6
        with:
          name: portfolio
          path: .

      - name: Restore venv
        uses: actions/cache/restore@v4
        id: cache-venv
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install deps
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          pip install uv==0.8.13
          uv venv
          uv sync
          uv sync --group test

      - name: Run tests
        env:
          PORTFOLIO_SKIP_SECRET_KEY_CHECK: true
        run: |
          . .venv/bin/activate
          make test

      - name: Save venv
        uses: actions/cache/save@v4
        if: steps.cache-venv.outputs.cache-hit != 'true'
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ github.run_id }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: test
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11.9"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}

      - name: Download repo artifact
        uses: actions/download-artifact@v6
        with:
          name: portfolio
          path: .

      - name: Restore venv
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Pylint
        run: |
          . .venv/bin/activate
          pylint src stubs

      - name: Black
        run: |
          . .venv/bin/activate
          black --check .

      - name: Flake8
        run: |
          . .venv/bin/activate
          flake8 .

      - name: Restore Pyre cache
        uses: actions/cache/restore@v4
        if: env.PYRE_SKIP == 'false'
        with:
          path: .pyre
          key: pyre-cache

      - name: Pyre analysis
        if: env.PYRE_SKIP == 'false'
        run: |
          . .venv/bin/activate
          pyre --output=json | python3 -m json.tool

      - name: Pysa analysis
        if: env.PYRE_SKIP == 'false'
        run: |
          . .venv/bin/activate
          pyre --noninteractive analyze --no-verify --use-cache --output-format json

      - name: Save Pyre cache
        uses: actions/cache/save@v4
        if: env.PYRE_SKIP == 'false'
        with:
          path: .pyre
          key: pyre-cache

  pre-checks:
    name: Check if the app is eligable for deployment per Django standards
    runs-on: ubuntu-latest
    needs: test
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11.9"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}

      - name: Download repo artifact
        uses: actions/download-artifact@v6
        with:
          name: portfolio
          path: .

      - name: Restore venv
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ github.run_id }}

      - name: Check if app is compliant for deployment
        env:
          PORTFOLIO_SKIP_SECRET_KEY_CHECK: true
        run: |
          . .venv/bin/activate
          make check

      - name: Check if the migrations are backwards compatible
        env:
          PORTFOLIO_SKIP_SECRET_KEY_CHECK: true
        run: |
          . .venv/bin/activate
          make migrate-check
